version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: react-frontend
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true